/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Usman
 */
public class Manage_Employee extends javax.swing.JFrame {
    
    private int appuserPK = 0;
    int user;
    /**
     * Creates new form Manage_Userr
     */
    public Manage_Employee() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Manage Employees");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "Name", "Email", "Address", "Mobile Number"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 460, 480));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 325, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 325, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 325, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 325, -1));

        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 110, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jButton2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.black));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Employee ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_idActionPerformed(evt);
            }
        });
        getContentPane().add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 325, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (4).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        jButton2.setEnabled(false);
        try {
            
            Connection con = Conn.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from users ");
            
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("user_id"),rs.getString("name"),rs.getString("email"),rs.getString("address"),rs.getString("mobile")});
            }
            
        
        
        } 
        catch (SQLException ex) {
         
            JOptionPane.showMessageDialog(null, ex);
            System.out.println("EXception " + ex);
        }
            
            
            
        
    }//GEN-LAST:event_formComponentShown

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if(evt.getSource() == jButton1)
        {
            String name1=name.getText();
            String mobile1=mobile.getText();
            String email1=email.getText();
          //  String password1=password.getText();
            String address1=address.getText();
            
            
            Insert(name1,mobile1,email1,"pass", address1);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Object jTable1MouseClicked;
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        String name1 = model.getValueAt(index,1).toString();
        name.setText(name1);
        String mobile1= model.getValueAt(index,4).toString();
        mobile.setText(mobile1);
        String email1= model.getValueAt(index,2).toString();
        email.setText(email1);
        String address1= model.getValueAt(index,3).toString();
        address.setText(address1);
        String id =  model.getValueAt(index, 0).toString();
        appuserPK = Integer.parseInt(id);
        user_id.setText(id);
        
    //    password.setEditable(false);
    //    password.setBackground(Color.DARK_GRAY);
        
    jButton2.setEnabled(true);
        jButton1.setEnabled(false);
            
    }//GEN-LAST:event_jTable1MouseClicked

    public void update2(String name1)
    { 
          System.out.println("update2 check");
        Connection con = Conn.getCon();
        PreparedStatement st;
        try {
            System.out.println("try update2 check");
            //int u_id = Integer.parseInt(id);
            System.out.println("appuserPK : "+appuserPK);
           // st.con.prepareStatement("update users set name = '?'");
           st = con.prepareStatement("update users  set  name=('"+name1+"') where user_id = ('"+appuserPK+"')  ");
            System.out.println("before name");
            
           st.executeUpdate();
           
              
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            System.out.println("EXception " + ex);
        }
        
    }
    
     public void update(String name1, String mobile1,String password1, String email1, String address1) {
          System.out.println("update check");
        Connection con = Conn.getCon();
        PreparedStatement st;
        try {
            System.out.println("try update check");
            //int u_id = Integer.parseInt(id);
            System.out.println("appuserPK : "+appuserPK);
        st = con.prepareStatement("update users  set  name=('"+name1+"') , email=('"+email1+"') , address= ('"+address1+"') ,password=('"+password1+"') , mobile = ('"+mobile1+"')   where user_id = ('"+appuserPK+"')  ");
        
           st.executeUpdate();
           JOptionPane.showMessageDialog(null,"Updated");
                
           
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            System.out.println("EXception " + ex);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(evt.getSource() == jButton2)
        {
            String name1=name.getText();
            String mobile1=mobile.getText();
            String email1=email.getText();
         //   String password1=password.getText();
            String address1=address.getText();
            //int  id = user_id.getText();
             // String user_id1 = String.valueOf(user_id);
              String user_id1 = user_id.getText();
              int id = 0;
              id=Integer.parseInt(user_id1 );
              
            
           
           //  String user_id1 = String.valueOf(user);
             System.out.println("button2: "+id);
            update(name1,mobile1,"pass",email1, address1);
          //  update2(name1);
            setVisible(false);
            new Manage_Employee().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_idActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.hide();
        setVisible(false);
        first_Page fp = new first_Page();
        fp.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    
    public void Insert(String name, String mobile, String email, String pass, String address) {

       try {
            Connection con = Conn.getCon();
            PreparedStatement st;
            
            Random rand = new Random();
             user = rand.nextInt(1000);
            st = con.prepareStatement("insert into users (user_id,name,email,address,password,mobile) values (?,?,?,?,?,?)");
            st.setInt(1, user);
            st.setString(2, name);
            st.setString(6, mobile);
            st.setString(3, email);
            st.setString(5, pass);
            st.setString(4, address);
            
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"User Updated");
            setVisible(false);
            new Manage_Employee().setVisible(true);
            

           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            System.out.println("EXception " + ex);
        }
    }

    
    public static void main(String args[]) {
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
